config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'static_pages#home'

  get '/about',    to: 'static_pages#about'
  get '/service',  to: 'static_pages#service'
  get '/blog',     to: 'static_pages#blog'
  get '/contacts', to: 'static_pages#contacts'
  get '/signup',   to: 'users#new'
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'
  get '/users',    to: 'users#index'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },format: { with: VALID_EMAIL_REGEX }, uniqueness:{ case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def service
  end

  def blog
  end

  def contacts
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Eureka Caffe!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def full_title(page_title = '')
        base_title = "Eureka Caffe"
        if page_title.empty?
            base_title
        else
        page_title + " | " + base_title
        end
    end    
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head lang="en">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Patricia Ciortea">
    <link rel="icon" href="https://cdn.onlinewebfonts.com/svg/img_255075.png" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% render 'partials/shim' %>
  </head>
  <body id="<%= yield(:title) %>">
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/partials/_card.html.haml
.card.col-md-3.zoom
    %img.card-img-top{:alt => "Card image", :src => src, :style => "width:100%", class: "#{title}=card"}/
    .card-body
        %h4.card-title= title
        %p.card-text.description= description
        %p.card-text.price= price 

app/views/partials/_footer.html.haml
%footer
  .container-fluid.opening
    .row
      .col-md-4
      .col-md-4.text-center
        %h3 Opening Hours
        %h6 Everyday 10 AM - 11 PM
      .col-md-4
  .container-fluid.contact
    .row
      .col-md-4.text-left
        %p Contact:
        %p eureka_caffe@example.com
        %p 0123-456-789
        %a.small{:href => "url"} Privacy policy

      .col-md-4.text-center
        %p Check our profiles:
        %i.fab.fa-facebook-f
        %i.fab.fa-instagram
        %i.fab.fa-twitter
      .col-md-4.text-right
        %p.small Copyright @Eureka Caffe 2018

app/views/partials/_header.html.haml
.jumbotron.text-center.jumbotron-wrapper
  %h1 Ordering food
  %i.fas.fa-utensils
  %p Lorem ipsum dolor sit amet, consectetur adipiscing elit

app/views/partials/_navbar.html.haml
%nav.navbar.navbar-expand-md.main-navbar.navbar-dark.fixed-top
  .container
    %a.navbar-brand.mb-0.h1{:href => "/"}
      .row
        %img.nav-logo{:alt => "logo", :src => "https://cdn.onlinewebfonts.com/svg/img_255075.png", :style => "height:50px;width:50px;"}/
        %span.nav-title
          EUREKA
          %br/
          CAFFE
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto.detail
        %li.nav-item
          = link_to "Home", root_path, class: "nav-link active", id: 'hover-bg'
        %li.nav-item.d-none.d-lg-block.d-xl-block
          %i.fas.fa-circle
        %li.nav-item
          = link_to "About", about_path, class: "nav-link  active", id: 'hover-bg'
        %li.nav-item.d-none.d-lg-block.d-xl-block
          %i.fas.fa-circle
        %li.nav-item
          = link_to "Service", service_path, class: "nav-link  active", id: 'hover-bg'
        %li.nav-item.d-none.d-lg-block.d-xl-block
          %i.fas.fa-circle
        %li.nav-item
          = link_to "Blog", blog_path, class: "nav-link  active", id: 'hover-bg'
        %li.nav-item.d-none.d-lg-block.d-xl-block
          %i.fas.fa-circle
        %li.nav-item
          = link_to "Contacts", contacts_path, class: "nav-link  active", id: 'hover-bg'
        %li.nav-item.d-none.d-lg-block.d-xl-block
          %i.fas.fa-circle
        - if logged_in?
          %li.nav-item= link_to "Users", users_path, class: "nav-link  active", id: 'hover-bg'
          %li.nav-item.d-none.d-lg-block.d-xl-block
            %i.fas.fa-circle
          %li.dropdown
            %a.nav-item.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", class: "nav-link  active", id: 'hover-bg'}
              Account
              %b.caret
            %ul.dropdown-menu.nav-menu
              %li.nav-item= link_to "Profile", current_user, class: "nav-link  active", id: 'hover-bg'
              %li.nav-item= link_to "Settings",  edit_user_path(current_user), class: "nav-link  active", id: 'hover-bg'
              %li.divider
              %li.nav-item= link_to "Log out", logout_path, method: :delete, class: "nav-link  active", id: 'hover-bg'
        - else
          %li.nav-item= link_to "Log in", login_path, class: "nav-link  active", id: 'hover-bg'

app/views/partials/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(@user.errors.count, "error")}.
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg

app/views/static_pages/about.html.haml
- provide(:title, "About")
= render 'partials/navbar'
.container-fluid.text-center.about-header
    %h1 About Us
    %h3 Great food. Great time.
.container.about-content
    .jumbotron
        .col-lg-10.col-md-10
            %h2 Our Story
            %h5 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            %p  Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.
= render 'partials/footer'

app/views/static_pages/blog.html.haml
- provide(:title, "Blog")
= render 'partials/navbar'
.container-fluid.special
    .row
        .col-lg-8.col-md-10.mx-auto.text-center
            %h1 Our Blog
            %span Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam
.container-fluid.blog-content
    .container.blog-description
        %h3 Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrude consectetur adipisicing elit, sed do eiusmod tempor incididunt.
    .container-fluid
        .row
            .col-lg-7.col-md-7
                %h1 Organic food
                %h6  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.
            .col-lg-5.col-md-5
                %img{:alt => "Organic Food", :src => "https://theecologist.org/sites/default/files/styles/inline_l/public/NG_media/405406.jpg?itok=He2m--3m"}/
        .row
            .col-lg-5.col-md-5
                %img{:alt => "Organic Food", :src => "https://theecologist.org/sites/default/files/styles/inline_l/public/NG_media/405406.jpg?itok=He2m--3m"}/
            .col-lg-7.col-md-7
                %h1 Organic food
                %h6  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.
        .row
            .col-lg-7.col-md-7
                %h1 Organic food
                %h6  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.
            .col-lg-5.col-md-5
                %img{:alt => "Organic Food", :src => "https://theecologist.org/sites/default/files/styles/inline_l/public/NG_media/405406.jpg?itok=He2m--3m"}/
        %br/
        %br/
= render 'partials/footer'

app/views/static_pages/contacts.html.haml
= render 'partials/navbar'
= render 'partials/header'
- provide(:title, "Contacts")
= render 'partials/footer'

app/views/static_pages/home.html.haml
= render 'partials/navbar'
.container-fluid.home
    .row.text-center
        .col-lg-12.text-message
            %h1 Welcome to Eureka Caffe
= render 'partials/footer'

app/views/static_pages/service.html.haml
= render 'partials/navbar'
= render 'partials/header'
- provide(:title, "Service")
%nav.navbar.nav-sort.navbar-expand-md
  .container
    .row
      %button.navbar-toggler.nav-button-2{"data-target" => "#collapsibleNavbar2", "data-toggle" => "collapse", :type => "button"}
        %i.fas.fa-bars
      #collapsibleNavbar2.collapse.navbar-collapse
        %ul.navbar-nav
          .col-lg-3.col-md-3.text-left
            %li.nav-item.dropdown
              %a#navbardrop.nav-link.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                CATEGORY
                %i.fas.fa-angle-down{:style => "color: #ff9900"}
              .dropdown-menu
                %a.dropdown-item{:href => "#"} Breakfast
                %a.dropdown-item{:href => "#"} Lunch
                %a.dropdown-item{:href => "#"} Dinner
          - ['SORTING', 'VEGETARIAN'].each do |category|
            .col-lg-3.col-md-3
              %li.nav-item.dropdown
                %a#navbardrop.nav-link.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  = category
                  %i.fas.fa-angle-down{:style => "color: #ff9900"}
                .dropdown-menu
                  %a.dropdown-item{:href => "#"} Entrees
                  %a.dropdown-item{:href => "#"} Second Courses
                  %a.dropdown-item{:href => "#"} Salads
                  %a.dropdown-item{:href => "#"} Deserts
          .col-lg-3.col-md-2
            %li.nav-item.dropdown
              %a#navbardrop.nav-link.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :style => "color: black"}
                PRICE
                %span.rangeValues
          .col-lg-3.col-md-2
            %li.nav-item.dropdown
              %section.range-slider{ data: { target: '.rangeValues' } }
                %input{:max => "100", :min => "0", :step => "1", :type => "range", :value => "5"}/
                %input{:max => "100", :min => "0", :step => "1", :type => "range", :value => "80"}/

%br/
.container.text-center
  .row.row-top
    = render 'partials/card', title: 'Pasta Carbonara', description: 'Second Courses', price: '$9.00', src: 'http://miapasta.com/wp-content/themes/miapasta/images/menu/carbonara.png'
    = render 'partials/card', title: 'Steak', description: 'Second Courses', price: '$25.00', src: 'http://www.canisiusstroop.nl/en/wp-content/uploads/2016/03/34981064_l.png'
    = render 'partials/card', title: 'Chicken Special', description: 'Second Courses', price: '$18.00', src: 'https://www.eatthe80.com/content/uploads/media/images/site/plate.png'
    = render 'partials/card', title: 'Lasagna', description: 'Second Courses', price: '$20.00', src: 'https://www.pizzahut.com.cy/uploads/images/menu/lasagne%20bites_bolognaise_1443589071.png'
  .row.row-bottom
    = render 'partials/card', title: 'Pasta Prosciutto', description: 'Second Courses', price: '$12.00', src: 'http://pngimg.com/uploads/pasta/pasta_PNG96.png'
    = render 'partials/card', title: 'Pizza Margherita', description: 'Pizza', price: '$17.00', src: 'http://eatcaulipower.com/sites/default/files/product-images/Pizza-Margherita_1.png'
    = render 'partials/card', title: 'Caesar Salad', description: 'Salads', price: '$14.00', src: 'http://gzpizza.ca/wp-content/uploads/2017/09/Salad.png'
    = render 'partials/card', title: 'Legumes Soup', description: 'Entrees', price: '$7.00', src: 'https://zubuchon.com/wp-content/themes/ZubuChon/images/menu/soups/kalabasa-soup.png'
  %br/
= render 'partials/footer'

app/views/users/_user.html.haml
%li
  = link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    | #{link_to "delete", user, method: :delete, data: { confirm: "You sure?" }}

app/views/users/edit.html.haml
- provide(:title, "Edit user")
.container
  %h1 Update your profile
  .row
    .col-md-3
    .col-md-6
      = form_for(@user) do |f|
        = render 'shared/error_messages'
        = f.label :name
        = f.text_field :name, class: 'form-control'
        = f.label :email
        = f.email_field :email, class: 'form-control'
        = f.label :password
        = f.password_field :password, class: 'form-control'
        = f.label :password_confirmation, "Confirmation"
        = f.password_field :password_confirmation, class: 'form-control'
        = f.submit "Save changes", class: "btn btn-primary"

app/views/users/index.html.haml
- provide(:title, 'All users')
= render 'partials/navbar'
.jumbotron.text-center.jumbotron-wrapper
  %h1 All Users
  %i.fas.fa-utensils
  %p Lorem ipsum dolor sit amet, consectetur adipiscing elit
.container.users-container
  %ul.users
    = render @users
.container.container-paginate
  .row
    .col-md-4
    .col-md-4
      = will_paginate @users, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer
    .col-md-4
= render 'partials/footer'

app/views/users/new.html.haml
- provide(:title, 'Sign up')
.container-fluid.login.layer
  .row
    .col-md-4
    .col-md-4
      %h1 Join Us
      .jumbotron
        %h1 Sign up
        = form_for(@user) do |f|
          = render 'shared/error_messages'
          = f.label :name
          = f.text_field :name, class: 'form-control'
          = f.label :email
          = f.email_field :email, class: 'form-control'
          = f.label :password
          = f.password_field :password, class: 'form-control'
          = f.label :password_confirmation, "Confirmation"
          = f.password_field :password_confirmation, class: 'form-control'
          = f.submit "Create my account", class: "btn btn-primary"

app/views/users/show.html.haml
- provide(:title, @user.name)
= render 'partials/navbar'
.jumbotron
  %h1 #{@user.name}, #{@user.email}
= render 'partials/footer'